# Generated by Django 6.0.5 on 2026-06-21 17:12

from django.db import migrations, models


def migrate_role_values(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='admin').update(role='senior')
    CustomUser.objects.filter(role='viewer').update(role='junior')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_issuethread_threadmessage'),
    ]

    operations = [
        migrations.RunPython(migrate_role_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior')], default='junior', max_length=10),
        ),
    ]
