# Generated by Django 6.0.5 on 2026-06-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_globalanalysisschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='juniorsubmission',
            name='relative_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
