# Generated by Django 6.0.5 on 2026-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_juniorsubmission_relative_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="juniorsubmission",
            name="rag_document_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
