# Generated by Django 6.0.5 on 2026-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_juniorsubmission_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password_reset_token",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
