# Generated by Django 6.0.5 on 2026-07-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior')], db_index=True, default='junior', max_length=10),
        ),
    ]
