from django.urls import path

from .views import (
    AdminUserListView,
    AdminUserRoleUpdateView,
    CompleteMFALoginView,
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    FeedbackResolveView,
    GlobalScheduleView,
    JuniorClearView,
    JuniorFeedbackListView,
    JuniorFolderScheduleView,
    JuniorGitImportView,
    JuniorSubmissionAnalyzeView,
    JuniorSubmissionBatchUploadView,
    JuniorSubmissionDetailView,
    JuniorSubmissionListView,
    JuniorSubmissionUploadView,
    LogoutView,
    MFAInitialVerifyView,
    MFASetupView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RegisterView,
    SchedulerTriggerView,
    SeniorAnalysisByFolderView,
    SeniorAnalysisHistoryView,
    SeniorFeedbackCreateView,
    SeniorSubmissionListView,
    SessionCheckView,
    SubmissionByAnalysisIdView,
    SubmissionFeedbackListView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),

    path('mfa/verify-login/', CompleteMFALoginView.as_view(), name='mfa_complete_login'),
    path('mfa/setup/', MFASetupView.as_view(), name='mfa_setup'),
    path('mfa/activate/', MFAInitialVerifyView.as_view(), name='mfa_initial_verify'),

    path('password-reset/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('session/', SessionCheckView.as_view(), name='session_check'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('admin/users/', AdminUserListView.as_view(), name='admin_user_list'),
    path('admin/users/<int:user_id>/role/', AdminUserRoleUpdateView.as_view(), name='admin_user_role_update'),

    path('junior/upload/', JuniorSubmissionUploadView.as_view(), name='junior_upload'),
    path('junior/batch-upload/', JuniorSubmissionBatchUploadView.as_view(), name='junior_batch_upload'),
    path('junior/list/', JuniorSubmissionListView.as_view(), name='junior_list'),
    path('junior/detail/<int:submission_id>/', JuniorSubmissionDetailView.as_view(), name='junior_detail'),
path('submission-by-analysis/<str:analysis_id>/', SubmissionByAnalysisIdView.as_view(), name='submission_by_analysis'),
    path('junior/analyze/<int:submission_id>/', JuniorSubmissionAnalyzeView.as_view(), name='junior_analyze'),
    path('junior/clear/', JuniorClearView.as_view(), name='junior_clear'),
    path('junior/schedule-folder/', JuniorFolderScheduleView.as_view(), name='junior_schedule_folder'),
    path('junior/git-import/', JuniorGitImportView.as_view(), name='junior_git_import'),
path('junior/feedback/', JuniorFeedbackListView.as_view(), name='junior_feedback_list'),
path('junior/feedback/<int:submission_id>/', SubmissionFeedbackListView.as_view(), name='submission_feedback_list'),
path('analysis-history/', SeniorAnalysisHistoryView.as_view(), name='analysis_history'),
path('analysis-by-folder/<path:scan_folder>/', SeniorAnalysisByFolderView.as_view(), name='analysis_by_folder'),
path('senior/submissions/', SeniorSubmissionListView.as_view(), name='senior_submission_list'),
path('senior/feedback/<int:submission_id>/', SeniorFeedbackCreateView.as_view(), name='senior_feedback_create'),
path('feedback/<int:feedback_id>/resolve/', FeedbackResolveView.as_view(), name='feedback_resolve'),
path('scheduler/config/', GlobalScheduleView.as_view(), name='scheduler_config'),
path('scheduler/trigger/', SchedulerTriggerView.as_view(), name='scheduler_trigger'),
]
